### ISSUE TITLE
Guardian: arm_failure_count() has no caller anywhere - fleet dashboard has no signal on reconcile failures

### ISSUE THREAD

**Issue by FortitudeEtc** [Tr3kkR/Yuzu#4062]
## Context

Discovered during governance on #4021 (sre, Gate 6). `agents/core/src/guardian_engine.cpp`'s `arm_failures_` atomic counter (and its `arm_failure_count()` accessor) is incremented on every reconcile/sweep failure — including the new failure paths this branch adds (a `list_entries()` sweep failure, a `del_keys()` undercount) — but has **no caller anywhere**, confirmed both on this branch and on `origin/dev`. It is not read into `GuaranteedStateStatus` (the proto has no such field) and is not one of the 4 tags in `guardian_health_heartbeat.hpp`'s `yuzu_fleet_guardian_*` family (the actual working fleet-visibility mechanism for Guardian).

The code's own comment at `guardian_engine.cpp:~1061` ("arm_failures_ ... surfaced via the heartbeat, item 9") is currently false — pre-existing, not a regression introduced by #4021, but this branch's own new failure paths inherit the same zero-visibility gap.

## Acceptance criteria

- Wire `arm_failure_count()` into the fleet-visibility tag family (agent-side emitter in `guardian_health_heartbeat.hpp`, server-side table/column in `server/core/src/guardian_health_fleet_tags.hpp`, a pin test, and an alert-rule/doc entry).
- Fix the stale comment at `guardian_engine.cpp:~1061` in the same change.

## Origin

Governance run on #4021, 2026-09-06 (Gate 6 sre). Dedupe searched: "arm_failure_count heartbeat" — no existing issue found.
