### ISSUE TITLE
GCC 13 build break in guardian_spark_runtime.cpp — unordered_set<string> from string_view iterators (blocks the workflow canary)

### ISSUE THREAD

**Issue by fjarvis** [Tr3kkR/Yuzu#2484]
`agents/core/src/guardian_spark_runtime.cpp:764` does not compile under **GCC 13 / libstdc++ 13**:

```cpp
std::unordered_set<std::string> GuardianSparkRuntime::lifecycle_event_ids() const {
    std::lock_guard<std::mutex> ob{outbox_mu_};
    const auto present = lifecycle_log_.event_id_set(); // unordered_set<string_view>
    return std::unordered_set<std::string>(present.begin(), present.end());
}
```

libstdc++ 13's `_Hashtable::_S_forward_key` rejects the `string_view` → `string` conversion on the range-insert path:

```
/usr/include/c++/13/bits/hashtable.h:890:39: error: could not convert
  'std::forward<const basic_string_view<char>&>((* & __k))'
  from 'const std::basic_string_view<char>'
  to 'std::__conditional_t<true, std::__cxx11::basic_string<char>, const std::basic_string_view<char>&>'
```

GCC 14+ accepts it, which is why every other Linux leg is green — the main CI Linux leg is **gcc-15**.

## Why this surfaced now, and not on dev

The **Workflow canary (GHA-hosted ubuntu-24.04)** job is the only leg that builds with the distro's system GCC 13. It is gated on CI-infrastructure changes, so it is `skipped` on ordinary `dev` pushes and on most PRs. It only runs when a PR touches CI infra — so the break has been sitting on `dev` since it landed without any leg exercising it.

Observed on PR #2394 (which touches `.github/workflows/ci.yml` for an unrelated macOS change and therefore triggers the canary): run 30169901489, job 89709186301. That PR touches no agent code — `git diff --name-only origin/dev...HEAD | grep guardian_spark` is empty — and the failing line is present verbatim on `origin/dev`.

Introduced by f65785eb (2026-07-22, "refactor(guardian): return the staging snapshot and its drop count as one value").

## Fix

One line — construct explicitly rather than relying on the heterogeneous range-insert:

```cpp
std::unordered_set<std::string> out;
out.reserve(present.size());
for (auto sv : present)
    out.emplace(sv);
return out;
```

## Worth deciding separately

The canary's trigger means a GCC 13 portability break can only ever be discovered by an unrelated CI-infra PR, at which point it blocks that PR for reasons its author cannot act on. Either the declared minimum compiler should be raised to GCC 14 (CLAUDE.md currently says **GCC 13+**), or a GCC 13 leg should run on a cadence that actually catches this. #2185 already covers canary trigger/caching concerns and may be the right home for that decision.
