### PR TITLE
feat(network): /network device/local-link health dashboard — measurement-first (N1)

### PR DESCRIPTION
**Pull request by FortitudeEtc**
## What this is

A dedicated `/network` dashboard — continuous, fleet-wide **device / local-link network health**, measured on each agent from kernel TCP counters. No packet capture, no flow export, no central appliance: measurement happens at the edge and only thin device-aggregate facts leave the device.

This bundles the full N1 feature: v1 mockups, the server read-model + routes + UI (slices 1–3), Linux heartbeat facts (slice 4a), and the **measurement-first signal rework + opt-in per-connection warehouse foundation** (4b).

## The headline: an honest signal

The earlier device-aggregate retransmit signal was the connections' **absolute lifetime ratio**, which is empirically diluted to noise (30% real loss moved it 0.14%→0.37% on a netem rig). 4b replaces it with a **smoothed interval delta** (ΔΣretransmits / ΔΣsegments over recent heartbeats), which cleanly separates 0% / 4% / 12% loss. The threshold-based `net_degraded` is **retired** — a trustworthy degraded *classification* needs a real-fleet baseline to calibrate (healthy internet links retransmit a little), so v1 is **measurement-first**: it ships honest evidence and defers the degraded classification, the co-occurrence "where's the pain" headline, and per-destination localization to later slices.

## Opt-in per-connection warehouse (foundation, unconsumed in v1)

A `netqual` TAR capture source (Linux netlink `INET_DIAG` TCP_INFO → `$NetQual_Live`), **default off** (`netqual_enabled`), **bucket-only** (a coarse destination class — loopback / private / public — is stored; raw addresses are dropped at the edge), per-tick top-N capped. The substrate for the deferred per-destination drill; nothing consumes it yet.

## Validation
- Empirical signal validation on a Linux netem rig (0% → ~0, 4% → 3.8%, 12% → 7.25%).
- Windows agent + tar + server suites green; the Linux netlink path compiles on gcc 15.2.
- Verified the exact committed state builds + all suites pass in isolation.

## Governance
Full `/governance` pipeline (8 gates) — **no CRITICAL/HIGH**. Hardening applied in-PR: netlink message-length bounds guard + cross-dump seq discard; `remote_bucket` CGNAT + IPv4-mapped handling; `net_degraded` gauge made absent-not-zero + a `net_retrans_reporting` denominator; opt-in insert log-and-continue.

### Deferred follow-ups (not block-merge)
- Make the netlink message-walk buffer-injectable for ASan regression testing.
- `SqliteTxn`/`SqliteStmt` RAII for the netqual insert.
- Enable-path requirements before any operator-visible toggle ships: a distinct audit verb for the collection toggle, purge-on-disable, and a time-based retention cap.

## Privacy posture
Per-connection collection is opt-in/default-off (usage-class telemetry), stores only a destination *class* (never a raw address/host/port), records the owning process by image name only, and is bounded by a top-N cap + row-count retention.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by fjarvis — CHANGES_REQUESTED** [review]
## Review — requesting changes

Nice, well-structured feature, and the **server half is genuinely clean** — it compiles, has good unit coverage (`[network]` 101 assertions / 19 cases pass), the netlink aliasing is handled correctly (memcpy into an aligned local, not a cast), fd/socket/`FILE*` ownership is RAII-correct, forged heartbeat-tag validation is sound, XSS escaping is present and tested, the untrusted-SQL chokepoint is untouched, and privacy bucketing drops raw addresses at the edge. But it can't merge as-is — the agent + TAR plugin don't build on our canonical Linux toolchain, and there are a couple of contract/authz gaps to close.

I built the PR head offline against our in-tree vcpkg on Ubuntu 24.04 / gcc-13 / glibc-2.39 and ran the server suite.

### 🔴 Blocker — agent + TAR plugin do not compile on Ubuntu 24.04 / gcc-13 / glibc-2.39
`net_quality_sampler.cpp:128,142` and `tar_network_collector.cpp:482,502` read `tcp_info::tcpi_segs_out`. That field exists only in the kernel uapi `<linux/tcp.h>` (line 266), **not** in glibc 2.39's `<netinet/tcp.h>` — which is the header actually `#include`d (`net_quality_sampler.cpp:18`). There's no `-Werror`; these are hard errors:

```
net_quality_sampler.cpp:128:67: error: 'struct tcp_info' has no member named 'tcpi_segs_out'
tar_network_collector.cpp:482:47: error: 'struct tcp_info' has no member named 'tcpi_segs_out'
```

You can't just add `<linux/tcp.h>` — it and `<netinet/tcp.h>` both define `struct tcp_info` and clash. Decode the field you need from a Linux-UAPI representation by offset (you already memcpy the kernel struct), or isolate the kernel-header include in a TU that doesn't pull in the glibc definition. Since netlink is the Linux-only producer of this telemetry, the broken path is the feature's entire data source.

⚠️ This slipped through because **CI only ran `cla-check` on this PR — the build matrix never executed** (`gh pr checks 1441`). Worth a separate look at why the Tier-1 build legs didn't trigger.

Downstream of this: the agent + TAR unit suites depend on `yuzu_agent_core_dep`, so they can't build either — which means the **privacy / names-only / signal-discipline claims are currently untested** at this head.

### Should fix before merge
- **A1 machine-readable parity is missing.** `/fragments/network/overview` and `/fragments/network/devices` return HTML only — no `/api/v1/network/*` JSON sibling and no MCP tool, unlike the DEX-perf dashboard this mirrors, which ships both `/api/v1/dex/perf/*` and three MCP tools. `docs/agentic-first-principle.md` §A1 gates every new fragment on this. Add permission-gated JSON variants (A4 envelope + OpenAPI), and consider the MCP sibling.
- **Device drill doesn't scope to management-group visibility.** Both `/fragments/network/*` gate only on `perm_fn_("GuaranteedState","Read")`; the snapshot (`server.cpp:7980-8016`) is built from all registry + health devices with no `get_visible_agents()` filter. A principal with global `GuaranteedState:Read` but restricted device visibility would see out-of-scope agent IDs + network facts. This matches the existing DEX fleet-wide surface, so it may be intentional for `GuaranteedState:Read` holders — but if management-group visibility is meant to scope this permission, both this and DEX need the filter. Let me know which way this should go.

### Worth addressing (non-blocking)
- **`net_quality_sampler.cpp:119`** lacks the `nlmsg_len >= NLMSG_LENGTH(sizeof(inet_diag_msg))` guard that its sibling `tar_network_collector.cpp:449` has (same comment, same risk). `RTA_OK` saves it today and the source is kernel-trusted, but the asymmetry is a foot-gun — please mirror the guard.
- **`rtts_ms`** in the sampler grows one entry per TCP connection with no cap, while the TAR tier caps at `kNetQualTopN=50`. Add a bound.
- **Throughput double-counts stacked interfaces.** `net_quality_sampler.cpp:161` sums every interface except `lo`, so bridges/veth/VPN count the same bytes multiple times. Fine for "measurement-first v1" if documented, but it makes cross-device comparisons topology-dependent.
- `docs/user-manual/network.md:62-63` says `yuzu_fleet_net_degraded` "reads 0" when not classified, but the code + `metrics.md:356` make the series **absent**. Fix the doc — absence must not be read as healthy.
- `NetPerfSnapshot::available_keys` / the cohort `key`/`cohort_value` params are wired but `network_ui.cpp` renders no picker (DEX has one at `dex_perf_ui.cpp:268-310`). Render it or drop the unused surface for now.

Happy to re-check the agent/TAR compile + privacy tests once the `tcpi_segs_out` break is fixed.

**Comment by FortitudeEtc** [comment]
Thanks @fjarvis — all blocking and non-blocking items are addressed, the A1 parity gap is closed, and there's **one design question** I'd like your call on (visibility scoping). The work landed in `c03ca298` (blocker + nits), `b13befb6` (JSON/MCP parity), and `edf99a52` (governance hardening), and the branch is now up to date with `dev`.

## 🔴 Blocker — `tcpi_segs_out` on glibc 2.39 — fixed
You were exactly right. `tcpi_segs_out` is absent from glibc 2.39's `<netinet/tcp.h>` (Ubuntu 24.04 / gcc-13), and `<linux/tcp.h>` can't be added — it re-defines `struct tcp_info`, clashing with the `<netinet/tcp.h>` we need for `TCP_ESTABLISHED`.

Fix: a new `agents/core/include/yuzu/agent/linux_tcp_info.hpp` — an offset-asserted `LinuxTcpInfo` POD mirroring the kernel uapi `tcp_info` prefix through `tcpi_segs_out`, with `static_assert`s pinning every read field's offset (+ `is_trivially_copyable` / `is_standard_layout`). Both `net_quality_sampler.cpp` and `tar_network_collector.cpp` now `memcpy` the netlink payload into it, dropping all dependence on glibc's struct.

**Verified on real glibc 2.39** — `g++ -c` in an `ubuntu:24.04` container, with the pinned offsets cross-checked against the kernel's own `<linux/tcp.h>`. (My earlier check used `-fsyntax-only` on newer-glibc rigs, which is exactly why this slipped through — lesson taken.)

## Non-blocking nits
- **Missing `nlmsg_len` guard in the sampler** — fixed; it now carries the full `nlmsg_seq != family || nlmsg_len < NLMSG_LENGTH(sizeof(inet_diag_msg))` guard, matching `nq_collect` (also closes a latent cross-family double-count).
- **`rtts_ms` unbounded** — fixed; capped at `kMaxRttSamples = 4096` (it feeds a single median, so it can be larger than TAR's per-row `kNetQualTopN=50`).
- **`network.md` "reads 0" for `yuzu_fleet_net_degraded`** — fixed; documented as **absent** (`recompute_metrics` clears + re-emits only when an agent reports the retired tag), matching `metrics.md`.
- **Cohort params with no picker** — fixed; the devices fragment now renders the cohort `<select>` + a drillable cohort cell (the params were live, just UI-unreachable), with a render test for the picker branch.
- **Throughput double-counts stacked interfaces** — **documented rather than filtered** (code comment + `network.md`). I deliberately didn't add a virtual-interface name filter: it's fragile across distros/orchestrators and would wrongly drop a VPN `tun` an operator cares about. v1 ships it as an honest coarse upper bound; accurate per-interface/route attribution is a later warehouse slice. Happy to revisit if you'd rather have the filter.

## Should-fix (a) — A1 machine-readable parity — done
Added the JSON + MCP siblings, mirroring the DEX-perf F2a pattern file-for-file (`b13befb6`):
- REST `GET /api/v1/network/fleet` + `GET /api/v1/network/devices` (in the OpenAPI spec, A2 discovery).
- MCP `get_network_fleet` + `list_network_devices`.

Both gate `GuaranteedState:Read`, reuse the existing memoized `NetPerfFn` provider (one closure now feeds fragments + REST + MCP, so they can't disagree), and are not audited (device link-health, matching DEX-perf + the un-audited fragments). Cohort handling mirrors the **fragment** (`key`, empty default, length guard), not DEX-REST's `cohort_key` / `validate_key`.

## Should-fix (b) — visibility scoping — design question
Both fragments (and now the REST/MCP siblings) gate on `GuaranteedState:Read` and build the snapshot from **all** devices — no `get_visible_agents()` filter. As you noted, this **matches the DEX surface exactly**, so it reads as intentional fleet-wide visibility for machine-health aggregates.

My lean: keep it fleet-wide for consistency with DEX-perf — these are device-aggregate link-health numbers, not behavioral/PII data (covered by the SOC 2 machine-health audit-exemption note). But it's a genuine cross-operator call. **If you'd prefer management-group scoping**, I'd apply it consistently across fragments + REST + MCP **and** the DEX-perf siblings (so the two surfaces don't diverge), as its own change rather than scope-narrowing only the network surface here. Which way do you want it?

## Context
- **CI:** the branch was conflicting with `dev`, which stopped GitHub from building the test-merge ref, so the Tier-1 matrix never scheduled (CLA ran via `pull_request_target`). Resolved — the branch is current with `dev` and the full matrix is green.
- A pre-existing `test_dex_routes.cpp` **date-bomb** (route fragments filter a now-relative 7d window; hardcoded June-8/9 seeds aged out) was fixed in parallel (#1448) and is on the branch.
- Ran the full `/governance` pipeline on the new work — clean (no CRITICAL/HIGH); the one blocking finding (untested picker markup) + the should-fixes are all in `edf99a52`. Two non-blocking follow-ups filed: #1449 (provider-fault resilience, shared with DEX-perf) and #1450 (pre-existing CHANGELOG hygiene).

**Review by fjarvis — APPROVED** [review]
## Re-review — approving

All blocking findings are resolved. Re-reviewed at `d3d5cd0d` with a local offline build (gcc-13 / glibc-2.39) + test run; CI is fully green.

**Blockers — fixed:**
- **CRITICAL build break (`tcp_info::tcpi_segs_out`)** → the new `linux_tcp_info.hpp` is the right fix: a portable, ABI-pinned `LinuxTcpInfo` (field offsets locked by `static_assert`, memcpy'd not cast, no glibc/kernel header collision), and the comment explicitly calls out the newer-glibc-rig failure mode that let it ship green before. Local build clean (exit 0).
- **HIGH A1 parity** → `GET /api/v1/network/{fleet,devices}` + OpenAPI + MCP `get_network_fleet`/`list_network_devices` + REST/MCP docs + tests. New handlers are `GuaranteedState:Read`-gated, input-validated (token allowlists, length-guarded key, robust `from_chars` limit → 400/clamp 500), A4 error envelope.
- **HIGH agent/TAR tests** → build and pass (`[network]` 203 assertions / 26 cases; mcp 89/10).

**MEDIUM/LOW — handled:**
- Management-group visibility → resolved as a documented named policy decision (SOC2 F2a→N1): aggregate fleet machine-health reads are deliberately fleet-wide for the access-reviewed `GuaranteedState:Read` role, with the fleet-enumeration as an accepted residual risk + compensating controls (web access-log + MCP audit), consistent with the shipped DEX surface. That answers the open product question I'd raised.
- Throughput double-count documented as a deliberate coarse upper-bound; netlink length guard added; `rtts` capped (4096); degraded-gauge doc corrected (absent ≠ 0); cohort picker now rendered.

No new issues in the delta. Nice work on the static_assert ABI guard and the near-2× test growth. Approving.
